[package]
name = "shufflekeys-ui"
version = "0.1.0"
description = "ShuffleKeys Desktop UI"
authors = ["Alain"]
license = "MIT"
edition = "2021"

[lib]
name = "shufflekeys_ui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.0", features = [] }
tauri-plugin-shell = "2.0"
tauri-plugin-log = "2.0"
tauri-plugin-process = "2.0"
shufflekeys = { path = ".." }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
